{{- /*
common.hook defines a hook.

This is to be used in a 'metadata.annotations' section.

This should be called as 'template "common.metadata.hook" "post-install"'

Any valid hook may be passed in. Separate multiple hooks with a ",".
*/ -}}
{{- define "common.hook" -}}
"helm.sh/hook": {{printf "%s" . | quote}}
{{- end -}}

{{- define "common.annote" -}}
{{- range $k, $v := . }}
{{ $k | quote }}: {{ $v | quote }}
{{- end -}}
{{- end -}}

{{- define "common.annotations.deployment" -}}
{{- $extended := default (dict) .Values.solution -}}
{{- $lifecycle := default (dict) .Values.lifecycle -}}
{{- $configmapTemplate := (print $.Template.BasePath "/configmap.yaml") -}}
checksum/config: {{ include $configmapTemplate . | sha256sum | trunc 63}}
{{- $prometheus := default (dict) .Values.prometheus -}}
{{- if $prometheus }}
prometheus.io/scrape: "true"
prometheus.io/path: "{{ default "/actuator/prometheus" $prometheus.path }}"
prometheus.io/port: "{{ default "8080" $prometheus.port }}"
{{- end -}}
{{- end -}}
