{{- define "common.security.context" -}}
{{- $context := default (dict) .Values.securityContext -}}
{{- $runAsUser := ternary $context.runAsUser 1001 (hasKey $context "runAsUser") -}}
{{- $runAsGroup := ternary $context.runAsGroup $runAsUser (hasKey $context "runAsGroup") -}}
{{- $fsGroup := ternary $context.fsGroup 1001 (hasKey $context "fsGroup") -}}
{{- $runAsNonRoot := ternary $context.runAsNonRoot true (hasKey $context "runAsNonRoot") -}}
securityContext:
  runAsUser: {{ $runAsUser }}
  runAsGroup: {{ $runAsGroup }}
  fsGroup: {{ $fsGroup }}
  runAsNonRoot: {{ $runAsNonRoot }}
{{- end -}}
