{{- define "common.vmServiceScrape.tpl" -}}
{{- $monitoring := default (dict) .Values.monitoring -}}
{{- $monitoringEnabled := true -}}
{{- if hasKey $monitoring "enabled" -}}
  {{- $monitoringEnabled = $monitoring.enabled -}}
{{- end -}}
{{- if $monitoringEnabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
{{ template "common.metadata" . }}
spec:
  selector:
    matchLabels: {{- include "common.labels.selector" . | nindent 6 }}
  endpoints:
    - interval: {{ default "60s" $monitoring.interval | quote }}
      port: {{ default "http" $monitoring.port | quote }}
      path: {{ default "/metrics" $monitoring.path | quote }}
{{- end -}}
{{- end -}}
{{- define "common.vmServiceScrape" -}}
{{- template "common.util.merge" (append . "common.vmServiceScrape.tpl") -}}
{{- end -}}
