apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: argocdrepos.githubapp.kharkevich.org
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  group: githubapp.kharkevich.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                privateKeySecret:
                  type: string
                argoCDRepositories:
                  type: array
                  items:
                    type: object
                    properties:
                      repository:
                        type: string
                      namespace:
                        type: string
            status:
              type: object
              properties:
                token:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: argocdrepos
    singular: argocdrepo
    kind: ArgoCDRepo
    shortNames:
      - gha
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dockerconfigjsons.githubapp.kharkevich.org
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  group: githubapp.kharkevich.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                privateKeySecret:
                  type: string
                dockerConfigSecrets:
                  type: array
                  items:
                    type: object
                    properties:
                      secret:
                        type: string
                      namespace:
                        type: string
                      registry:
                        type: string
                        default: "ghcr.io"
                      username:
                        type: string
                        default: "x-access-token"
            status:
              type: object
              properties:
                token:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: dockerconfigjsons
    singular: dockerconfigjson
    kind: DockerConfigJson
    shortNames:
      - dcj
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ghss.githubapp.kharkevich.org
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  group: githubapp.kharkevich.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                token:
                  type: string
            status:
              type: object
              properties:
                expiresAt:
                  type: string
                  format: date-time
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: ghss
    singular: ghs
    kind: GHS
    shortNames:
      - ghs
